### ISSUE TITLE
build error WITH_PLASMA

### ISSUE THREAD

**Issue by blackPantherOS** [Shatur/optimus-manager-qt#78]
Cannot build with Qt 5.15.1 + Plasma 5.19.4 if WITH_PLASMA is ON
```
Scanning dependencies of target optimus-manager-qt
[ 65%] Building CXX object CMakeFiles/optimus-manager-qt.dir/optimus-manager-qt_autogen/mocs_compilation.cpp.o
[ 69%] Building CXX object CMakeFiles/optimus-manager-qt.dir/src/appsettings.cpp.o
[ 73%] Building CXX object CMakeFiles/optimus-manager-qt.dir/src/daemonclient.cpp.o
[ 76%] Building CXX object CMakeFiles/optimus-manager-qt.dir/src/main.cpp.o
[ 80%] Building CXX object CMakeFiles/optimus-manager-qt.dir/src/optimusmanager.cpp.o
In file included from /usr/include/qt5/QtCore/qflags.h:40,
                 from /usr/include/qt5/QtCore/QFlags:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimussettings.h:24,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.h:24,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:21:
/usr/include/qt5/QtCore/qmetaobject.h: In instantiation of ‘static QMetaEnum QMetaEnum::fromType() [with T = AppSettings::Gpu]’:
/home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:80:107:   required from here
/usr/include/qt5/QtCore/qmetaobject.h:231:9: error: static assertion failed: QMetaEnum::fromType only works with enums declared as Q_ENUM, Q_ENUM_NS, Q_FLAG or Q_FLAG_NS
  231 |         Q_STATIC_ASSERT_X(QtPrivate::IsQEnumHelper<T>::Value,
      |         ^~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/QMetaEnum:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:35:
/usr/include/qt5/QtCore/qmetaobject.h:234:61: error: ‘qt_getEnumMetaObject’ was not declared in this scope
  234 |         const QMetaObject *metaObject = qt_getEnumMetaObject(T());
      |                                         ~~~~~~~~~~~~~~~~~~~~^~~~~
/usr/include/qt5/QtCore/qmetaobject.h:234:61: note: suggested alternatives:
In file included from /usr/include/qt5/QtCore/qobject.h:54,
                 from /usr/include/qt5/QtCore/qsettings.h:43,
                 from /usr/include/qt5/QtCore/QSettings:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimussettings.h:25,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.h:24,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:21:
/usr/include/qt5/QtCore/qmetatype.h:1564:31: note:   ‘QtPrivate::qt_getEnumMetaObject’
 1564 |     template<typename T> char qt_getEnumMetaObject(const T&);
      |                               ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from /usr/include/qt5/QtCore/qobject.h:46,
                 from /usr/include/qt5/QtCore/qsettings.h:43,
                 from /usr/include/qt5/QtCore/QSettings:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimussettings.h:25,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.h:24,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:21:
/usr/include/qt5/QtCore/qnamespace.h:1868:5: note:   ‘Qt::qt_getEnumMetaObject’
 1868 |     QT_Q_ENUM(TabFocusBehavior)
      |     ^~~~~~~~~
In file included from /usr/include/qt5/QtCore/QMetaEnum:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:35:
/usr/include/qt5/QtCore/qmetaobject.h:235:42: error: ‘qt_getEnumName’ was not declared in this scope; did you mean ‘Qt::qt_getEnumName’?
  235 |         const char *name = qt_getEnumName(T());
      |                            ~~~~~~~~~~~~~~^~~~~
      |                            Qt::qt_getEnumName
In file included from /usr/include/qt5/QtCore/qobjectdefs.h:48,
                 from /usr/include/qt5/QtCore/qobject.h:46,
                 from /usr/include/qt5/QtCore/qsettings.h:43,
                 from /usr/include/qt5/QtCore/QSettings:1,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimussettings.h:25,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.h:24,
                 from /home/build/rpmbuild/SOURCES/optimus-manager-qt/src/optimusmanager.cpp:21:
/usr/include/qt5/QtCore/qnamespace.h:1868:5: note: ‘Qt::qt_getEnumName’ declared here
 1868 |     QT_Q_ENUM(TabFocusBehavior)
      |     ^~~~~~~~~
make[2]: *** [CMakeFiles/optimus-manager-qt.dir/build.make:186: CMakeFiles/optimus-manager-qt.dir/src/optimusmanager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/optimus-manager-qt.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
Build successful if  PLASMA is OFF

**Comment by Shatur** [comment]
Thanks!
